name: PHPStan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none

      - name: Validate composer
        run: composer validate --no-check-publish

      - name: Install composer dependencies
        run: |
          composer require --dev \
            "laravel/framework:12.*" \
            "orchestra/testbench:^10.9.0" \
            "pestphp/pest:^3.8.4" \
            "pestphp/pest-plugin-laravel:^3.2.0" \
            "pestphp/pest-plugin-arch:^3.1.1" \
            "larastan/larastan:^3.9.2" \
            "phpstan/phpstan:^2.1.32" \
            "phpstan/phpstan-phpunit:^2.0.7" \
            "phpstan/phpstan-deprecation-rules:^2.0.3" \
            --no-interaction --no-update
          composer update -W --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress --error-format=github
